### ISSUE TITLE
Mission section

### ISSUE THREAD

**Issue by aeimskei** [aeimskei/cyber-security-club#10]
* Is the short piece for Mission content ok?
* Has the Mission Statement been finalized?
* Button needs to be linked to the full Mission Statement.

<img width="1167" alt="screen shot 2018-07-10 at 10 22 20 am" src="https://user-images.githubusercontent.com/23747060/42526623-2f090ef2-842b-11e8-87d4-33fdd3d4f145.png">

**Comment by elam3** [comment]
Looks awesome. @NullOverride Do you think we should emphasis that our audience is both technical and non-technical?

I'm wondering how we can have that communicated.

Would it work if we revise the first sentence and have it say something like:
"... to prepare non-technical and technical students for careers in ..."

I wanted to mention non-technical first to give it that extra umph. What do you guys think?

**Comment by NullOverride** [comment]
Sounds like a great idea. Maybe we should make a checklist of points we want to make on the mission statement and see if we addressed all of them. Right now I have the button pop up a modal. As for the text, I just copied the stuff from the drive. 
![chrome_2018-07-10_13-46-31.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44521fae767200127b0949/125516c66e82c728ace21e0d46eb9c882c8f8696ddb9ee1be90da7d9781618227a49f77d3dd6b26af3006b1300051bff054a5556f9ab8d2ff5e56a74825a58e5d96c5f74c76e18adbbd14cbb13a632c91edbe2e3d7158abd7f37ed998e48341f001b88fd5830a69b43ce5af659ac.png)

**Comment by NanaRei** [comment]
Not about the pop up, which I like for now. Can we shorten the mission statement that is on the site to something like: 

Prepares students for careers in tech and cyber security through technical and non-technical trainings. Offers focused workshops and trainings on security concepts, soft skills, team and leadership skills. Access to job opportunities and more. Promotes diversity and inclusion. 

I don't know how the pop up works. So does the user just puts their mouse over the words and a pop up appears or do we need an icon or "here" to make the pop up work? Figure it out but let me know if the above statement makes it easier for readability and appearance.

**Comment by NullOverride** [comment]
How's this @NanaRei ? The "Read Full Statement" button will activate the pop-up upon clicking it on the same page. Otherwise, we can have that button link to another website or PDF file.

![chrome_2018-07-12_12-10-32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44521fae767200127b0949/125516c66e82c728ace21e0d46eb9c882c8f8696ddb9ee1be90da7d9781418227b49f27b3dd6b16af3006b1300051bff054a5556f9ab8d2ff5e56a74825a58e5d96c5f74c76e18adbbd14cbb13a632c91edbe2e3d7158abd7f37ed998d4f341f001b88fb5f37a79c48ce51f659ac.png)

**Comment by NanaRei** [comment]
Looks much better. Thanks Danny. What do you think Amy and Edison?
