### ISSUE TITLE
Cyber Camp 2018 page

### ISSUE THREAD

**Issue by aeimskei** [aeimskei/cyber-security-club#12]
* Create a new page specifically for this topic
* Could use stock photos
* Utilize content given by Kerrie (Google Drive)

* @elam3 want to give it a shot on the initial design?

**Comment by NanaRei** [comment]
I have the website from Cabrillo College who put together all the Cyber Camps (this is Irvin's website) https://www.baycyber.net and https://www.baycyber.net/cybercamps2018locations. I would like for us to create our own page and have Irvin link it to his site so we can feature our college on the list of other community colleges that are taking part in cyber camp. There are also very good images like the one with Sam (you can try and get that photo Amy). If you need the photos from the site, I can reach out to Irvin and ask for some of them. Also, is it possible to link a Google Photo to this page so we can upload pictures we take during the camp?

**Comment by NanaRei** [comment]
Let me know if you have any questions.

**Comment by aeimskei** [comment]
CyberCamp 2018 (link): https://www.baycyber.net/cybercamps2018locations

**Comment by aeimskei** [comment]
Sam's info (link): https://www.ccsf.edu/Info/Dir/cgi-bin/ccsfdirs.pl?words=Bowne,%20Samuel%20F%20%20%20&type=2&Semester=5

**Comment by aeimskei** [comment]
Sam's info, more (link): https://samsclass.info/contact.html
