### ISSUE TITLE
Competition Team

### ISSUE THREAD

**Issue by NanaRei** [aeimskei/cyber-security-club#20]
@aeimskei please place this link for the Competition Team: https://samsclass.info/140/140_S18.shtml. The user will click on the link and it takes them to Sam's page for the class CNIT 140, which is the class for students who want to compete. 

I will work on the small blurb for you and get it to you later today.

**Comment by aeimskei** [comment]
Hi Kerrie, just following up on whether you were able to create a blurb for the Competition Team.

* I added the Sam's link on the navbar dropdown for this team and also in it's section on the home page body.

**Comment by NanaRei** [comment]
The Cyber Security Club supports student competition teams who compete in the Western Regional Cyber Collegiate Defense Competition (WRCCDC), Collegiate Penetration Testing Competition (CPTC), and the National Cyber League (NCL), which offers students an opportunity to prepare for employment as security professionals. Students learn to work in teams to secure network infrastructure, develop defensive strategies, and make threat assessments in order to protect business operations from cyber attacks.

**Comment by NanaRei** [comment]
@aeimskei see above for the blurb.

**Comment by aeimskei** [comment]
@NanaRei thank you!
