### ISSUE TITLE
Fix layout issue, missing up on Internet Explorer Browser

### ISSUE THREAD

**Issue by aeimskei** [aeimskei/cyber-security-club#21]
@NullOverride  has already looked into this. Has bee asked to fix.
 "...problem with IE not properly handling the "d-sm-block" CSS property. "

![image](https://user-images.githubusercontent.com/23747060/43166239-e09e4b80-8f4a-11e8-8980-bcdc16842e57.png)
![image](https://user-images.githubusercontent.com/23747060/43166248-e76361bc-8f4a-11e8-82bf-17c9c4e534a7.png)

**Comment by aeimskei** [comment]
@NullOverride go ahead and try whatever you can to make it work by best your best judgement. You got this!

As for the accordion for Affiliates, go ahead and take that out. Kerrie said she wants to get rid of that and make to categories Projects and Teams.

* Projects = Cyber Camp 2018, Facebook CTF, Cyber Security Website
* Teams = Competition Team, Server Club

**Comment by NanaRei** [comment]
It looks beautifully on IE now. Thank you everyone for working on this. Really love how it looks and it is coming together wonderfully. I will push out the rest of my tasks soon. Get some rest everyone.
