### ISSUE TITLE
Social Media Channels

### ISSUE THREAD

**Issue by aeimskei** [aeimskei/cyber-security-club#22]
LinkedIn account needed.

Already have Slack and Twitter.

**Comment by aeimskei** [comment]
@NanaRei I can't get the LinkedIn Group link even after I accepted the invite.

**Comment by NanaRei** [comment]
https://www.linkedin.com/groups/13610764.

The LinkedIn group is public so you should be able to search and find it. Still figuring out how to load a picture for it. 

@aeimskei I elevated your privilege in the LinkedIn group to Manager. So you should be able to see everything.

**Comment by aeimskei** [comment]
Gotcha. All social medias are linked now.
