### ISSUE TITLE
Change back the club name 

### ISSUE THREAD

**Issue by NanaRei** [aeimskei/cyber-security-club#36]
@elam3  Amy informed me that you will be taking over for the website. 

Can you please change the name on the website back to Cyber Security Club. I miscommunicated and didn't mean to change the name to Cyber Club. The url will stay as ccsfcyberclub.org. Just that the website should be Cyber Security Club, that is our club's name. Please change it back to Cyber Security Club. Thank you. 

Also, did Amy leave any tasks incomplete? Please let me know. You and I will be communicating directly regarding the website development. If you have any questions, please contact me.

**Comment by NullOverride** [comment]
@NanaRei can you point out or screenshot where these instances are because i dont recall anything changing except the twitter feed.

**Comment by NanaRei** [comment]
![screen shot 2018-07-28 at 8 52 09 pm](https://user-images.githubusercontent.com/32437556/43362813-1b91e1ec-92a8-11e8-88b0-0acf5a42fa17.png)

**Comment by NanaRei** [comment]
Where it says Cyber Club, please change to Cyber Security Club

**Comment by NanaRei** [comment]
I think I might have to change our Twitter as well

**Comment by NanaRei** [comment]
I know it is confusing but I can explain later.

**Comment by NanaRei** [comment]
@NullOverride who will be finalizing the tasks? I know Amy was doing that but is it you or Edison now?
