### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by NanaRei** [aeimskei/cyber-security-club#39]
Update the Contacts to include club email: ccsfcyberclub@mail.ccsf.edu. Thank you.

**Comment by NullOverride** [comment]
Is this okay?
![ss (2018-08-30 at 07.44.43).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44521fae767200127b0949/125516c66e82c728ace21e0d46fb87da6bd0d3f8d7a4ef1be90ea0d4285267237e4af77f3ed1b061fd0e39111d0014f9121c4d4eeefcdb2fa2e56f268e540dbed9655e74c63c42a5b9814cec05a83c990dd4e8e8d51199a26867f5819d4e3614041d8afa5b3da39c4acb5cf64ff300.png)

**Comment by NanaRei** [comment]
Can you move the line up a little bit so it isn't sitting on top of those
buttons?

Kerrie

**Comment by NanaRei** [comment]
@aeimskei Is there anyway to move the email up a little bit so it isn't sitting on top of the buttons? Let me know. Thanks.

**Comment by aeimskei** [comment]
@NanaRei it should be in the footer using the envelope icon from Font Awesome. https://fontawesome.com/icons/envelope?style=solid

**Comment by NanaRei** [comment]
@aeimskei Thanks for the help. I will have @NullOverride take a look at it. 

Thanks again. You are the best.
