### ISSUE TITLE
Meeting Info

### ISSUE THREAD

**Issue by NanaRei** [aeimskei/cyber-security-club#40]
Change the Meeting Info button on our webpage to: 

CS/CNIT Job & Internship Fair
Sept. 4th, 4 - 6 pm 
MUB 140 

For the pop up, put: 

In place of our September meeting, please attend the CS/CNIT Job & Internship Fair.

The Cyber Security Club is sponsoring the event with Steve Nelson the CS/CNIT Career Specialist. Bring several copies of your resume, come and meet employers from various tech companies, and dress to impress. 

Go here to register to attend the event: http://bit.ly/CNITCSJobInternFair.

To volunteer and help with Set Up, Registration or Clean Up, contact the ccsfcyberclub@mail.ccsf.edu and on the subject line write CS/CNIT JOB FAIR.

**Comment by NullOverride** [comment]
![ss (2018-08-30 at 07.51.03).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44521fae767200127b0949/125516c66e82c728ace21e0d46fb87da6bd0d3f8d7a4ef1be90ea0d4285267237e4af67a3ed5b061fd0e39111d0014f9121c4d4eeefcdb2fa2e56f268e540dbed9655e74c63c42a5b9814cec05a83c990dd4e8e8d51199a26867f5819d4e3614041d8afa5b3da39048cb58f04ff300.png)

**Comment by NullOverride** [comment]
![ss (2018-08-30 at 07.51.45).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44521fae767200127b0949/125516c66e82c728ace21e0d46fb87da6bd0d3f8d7a4ef1be90ea0d4285267237e4af67a3ed1b661fd0e39111d0014f9121c4d4eeefcdb2fa2e56f268e540dbed9655e74c63c42a5b9814cec05a83c990dd4e8e8d51199a26867f5819d4e3614041d8afa5b3da39042ce5fff48f300.png)

**Comment by NanaRei** [comment]
Looks good.
