### ISSUE TITLE
People section

### ISSUE THREAD

**Issue by aeimskei** [aeimskei/cyber-security-club#7]
* Get a list of people you want to feature
* Title and names
* Brief bio
* Images (if possible, around 800x480 size)
* If the have links to link to their website, LinkedIn profile or GitHub (this is only if you guys want it)

<img width="1181" alt="screen shot 2018-07-10 at 10 11 00 am" src="https://user-images.githubusercontent.com/23747060/42526042-963e36d0-8429-11e8-929c-629bb45ee042.png">

Note: Waiting to add Kerrie to this (she hasn't accepted the GitHub contributor invite. 6/10)

**Comment by elam3** [comment]
Amy, Website is you! :D 

I think I'll have to fill in as an ICC Rep. I'm just worried that I won't be able to attend the mandatory meetings on Mondays afternoon because I'm signed up for 21 course units this Fall Semester.

I'll have a short bio ready by end of today. 

I'm a little worried for the image requirement. I don't have any decent images.

**Comment by NanaRei** [comment]
I can take over as ICC Rep. Don't worry about it. I can send you links to advisors LinkedIn bio and some instructors have their own webpages from the college as well. I can forward those to you.

**Comment by NanaRei** [comment]
Olivia Herriford https://www.linkedin.com/in/oliviaherriford/

**Comment by NanaRei** [comment]
Steven Nelson https://www.linkedin.com/in/steven-nelson-b59605b2/

**Comment by NanaRei** [comment]
I don't have info for Advisors: Richard Wu or Alan Wennersten. So for now I can just give you their bio but no picture.

**Comment by NanaRei** [comment]
Elizabeth Biddlecome https://www.linkedin.com/in/ebiddlecome/
Dylan James Smith https://www.linkedin.com/in/dylanjamessmith/

**Comment by aeimskei** [comment]
Meeting Jul 17th (Edison notes): 
Board of Advisors: 
Name -- Title
Richard Wu	-- 
Sam Bowne	--
Alan Wennersten --
Olivia Herrford --
Steven Nelson	-- 
(grab from linkedin)

Cyber Security Adminisrators
Kerrie Lu	-- President
Danny Mou	-- Treasurer
Edison Lam	-- Web Master
Dylan Smith	-- Student Advisor
Elizabeth Biddlecome	-- Student Advisor (To Be Instructor)

**Comment by NanaRei** [comment]
Would it be kind of weird to use a stock photo or a logo in place of the picture of the person. For instance, I can't find pics for Richard or Alan at all. I might have to scour the campus to find a pic for him or ask if he is willing to let me take a pic. For Alan, I am trying to see if I can find old photos of him as a student on the competition team.

**Comment by NanaRei** [comment]
![newday](https://user-images.githubusercontent.com/32437556/43041148-3c457d00-8d0c-11e8-8607-e783f0e5b1fb.jpg)
Olivia Herriford 
Cybersecurity Apprenticeship Grant Manager

**Comment by NanaRei** [comment]
![2016-11-06 10 38 14hh](https://user-images.githubusercontent.com/32437556/43041154-61bae606-8d0c-11e8-86ea-65112c05f984.jpg)
Alan Wennersten 
CNIT Instructor

**Comment by NanaRei** [comment]
![slide8](https://user-images.githubusercontent.com/32437556/43041157-7525e498-8d0c-11e8-8213-afec73e50e3b.png)
Elizabeth Biddlecome
Student Advisor

**Comment by NanaRei** [comment]
![dylan](https://user-images.githubusercontent.com/32437556/43041183-490dae80-8d0d-11e8-8986-66ba64c68ee1.jpeg)
Dylan James Smith
Student Advisor

**Comment by NanaRei** [comment]
![klu](https://user-images.githubusercontent.com/32437556/43041269-f2c4e86a-8d0f-11e8-8def-1b3c45c587e9.jpg)
Kerrie Lu
President & ICC Rep
