### ISSUE TITLE
Slack Integration?

### ISSUE THREAD

**Issue by aeimskei** [aeimskei/cyber-security-club#8]
* Kerrie said she wanted some form of feed displayed. It could be Slack or Twitter
* Place it in the section that has a red box

<img width="1168" alt="screen shot 2018-07-10 at 10 12 08 am" src="https://user-images.githubusercontent.com/23747060/42526224-199415a4-842a-11e8-98ff-0db84a1e61ef.png">

**Comment by NullOverride** [comment]
Slack might not be the way to go since many require a persistent application or subscription to be running that basically has access to the channels. I don't know at this point if we are going to use Slack at all for the website. We haven't made a Twitter feed yet so I just changed this into a scroll-able list for now. Let's wait for Kerrie's input for this section.

**Comment by NanaRei** [comment]
For Slack, is it possible to add only one of the channels like #announcements or #jobs and have that show up on the home page? The channels have been created but I haven't posted anything in there yet. Which channel would students be more interested in seeing, jobs or club announcements?

**Comment by NanaRei** [comment]
For the Advisors we can put something together for now. I can pull info off their LinkedIn page including their picture until they send something to us. We can use the info as a temporary placeholder and update at a later time.

**Comment by aeimskei** [comment]
Meeting Jul 17th (notes): Integrate Slack with Twitter
https://slack.com/apps/A0F7XDW93-twitter

Kerrie: Will setup Twitter account
Danny: Will code and integrate the API

**Comment by NullOverride** [comment]
Slack is being a bully. Don't know if it actually wants to help or not. At least the Twitter feed is good though. Also, added the affiliates section to the navbar dropdown.

![ss+(2018-07-17+at+08.31.11).jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44521fae767200127b0949/125516c66e82c728ace21e0d46fb87d16bd0d3f8d7a4ef14e90ca7df28526c23714af07a3ed4b261fd0e39111d0014f9121c4d4eeefcdb2fa2e56f268e540dbed9655e74c63c42a5b9814cec05a83c990dd4e8e8d51199a26867f5819d4e3914041d8afe553da4914dce5bf743f300.jpg)

**Comment by aeimskei** [comment]
Looks great @NullOverride!!! I'll merge it tonight. 
@NanaRei the two Tweets are showing. Thanks for setting up the account and thank you @NullOverride for getting this squared away. Looks beautiful. I'll see if I can make some small design tweaks for font.
![Screen Shot 2018-07-20 at 8.35.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae89fb057ed3e0011861ccc/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f36b7191a370f1112e4f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ebfd5690c27903919aaeb8a17be01ba21d84684b5efd948d2f42f67b6d5db1063474f4dcbed5727a29b41c95df549e04951a7113f61e3762431.png)
